# Generated by Django 5.2 on 2025-05-19 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adhd_stage',
            field=models.CharField(choices=[('early_stage', 'Early Stage'), ('school_stage', 'School Stage'), ('teen_stage', 'Adolescence & Adulthood')], default='early_stage', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.SmallIntegerField(blank=True, help_text='Alter des Patienten (optional, 3-99 Jahre)', null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(99)], verbose_name='Alter'),
        ),
    ]
