# Generated by Django 5.2 on 2025-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_patient_adhd_stage_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='_username',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
