# Generated by Django 5.2 on 2025-05-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_doctor__username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='_username',
        ),
    ]
